### ISSUE TITLE
RichEditor toolbar工具栏如何拓展？

### ISSUE THREAD

**Issue by pxim** [NSFI/ppfish-components#86]
RichEditor 工具栏如何拓展？
我想
加入 字体选择，h1、h2、h3选择；
可以 添加 自定义工具 按钮；

like 
![image](https://user-images.githubusercontent.com/5111701/160067989-492dee9d-2702-4a56-93e0-d5626184ad30.png)
![image](https://user-images.githubusercontent.com/5111701/160068022-11a08a77-ba23-4090-b7b5-f56009d83ec6.png)

quilljs里可以
![image](https://user-images.githubusercontent.com/5111701/160072216-c683182a-e25e-420f-8a74-45d14a7df6bd.png)
这样配置，
但是在ppfish-components - RichEditor 里这样配置不生效

@gtopia

**Comment by pxim** [comment]
@SummerOverture

**Comment by gtopia** [comment]
The RichEditor toolbar does not support font and header extensions. 

The properties of the toolbar cannot be directly passed to quill, because to support this extension we have to consider issues such as interactive visual consistency, multi-language, etc. 

We have no plan to support this extension for the time being.

**Comment by pxim** [comment]
> The RichEditor toolbar does not support font and header extensions.
> 
> The properties of the toolbar cannot be directly passed to quill, because to support this extension we have to consider issues such as interactive visual consistency, multi-language, etc.
> 
> We have no plan to support this extension for the time being.

如果直接在 你们这个组件里改代码，来达到我的目的，具体在哪个js文件里改？

**Comment by gtopia** [comment]
`source/components/RichEditor/src/toolbar.tsx`
